/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_acceuil (void);
GtkWidget* create_menu (void);
GtkWidget* create_gestionTrp (void);
GtkWidget* create_chercherTrp (void);
GtkWidget* create_calculerTrp (void);
GtkWidget* create_afficherTrp (void);
GtkWidget* create_supprimerTrp (void);
GtkWidget* create_gestionFK (void);
GtkWidget* create_AjouterFK (void);
GtkWidget* create_modifierFK (void);
GtkWidget* create_supprimerFK (void);
GtkWidget* create_rechercher1FK (void);
GtkWidget* create_afficher_rechercherFK (void);
GtkWidget* create_consulterFK (void);
GtkWidget* create_fenetre_acceuil (void);
GtkWidget* create_gestion_capteur (void);
GtkWidget* create_fenetre_Ajouter (void);
GtkWidget* create_fenetre_Modifier (void);
GtkWidget* create_fenetre_Alarmente (void);
GtkWidget* create_deffectueuxFK (void);
GtkWidget* create_marqueFK (void);
GtkWidget* create_gestion_ouvrier (void);
GtkWidget* create_Ajouter_ouvrier (void);
GtkWidget* create_modifier_ouvrier (void);
GtkWidget* create_supprimer_ouvrier (void);
GtkWidget* create_consulter_ouvrier (void);
GtkWidget* create_Presence_ouvrier (void);
GtkWidget* create_calcul_taux (void);
