/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"


int
main (int argc, char *argv[])
{
  GtkWidget *acceuil;
  /*GtkWidget *menu;
  GtkWidget *gestionTrp;
  GtkWidget *chercherTrp;
  GtkWidget *calculerTrp;
  GtkWidget *afficherTrp;
  GtkWidget *supprimerTrp;
  GtkWidget *gestionFK;
  GtkWidget *AjouterFK;
  GtkWidget *modifierFK;
  GtkWidget *supprimerFK;
  GtkWidget *rechercher1FK;
  GtkWidget *afficher_rechercherFK;
  GtkWidget *consulterFK;
  GtkWidget *fenetre_acceuil;
  GtkWidget *gestion_capteur;
  GtkWidget *fenetre_Ajouter;
  GtkWidget *fenetre_Modifier;
  GtkWidget *fenetre_Alarmente;
  GtkWidget *deffectueuxFK;
  GtkWidget *marqueFK;
  GtkWidget *gestion_ouvrier;
  GtkWidget *Ajouter_ouvrier;
  GtkWidget *modifier_ouvrier;
  GtkWidget *supprimer_ouvrier;
  GtkWidget *consulter_ouvrier;
  GtkWidget *Presence_ouvrier;
  GtkWidget *calcul_taux;*/
  GdkColor color;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  acceuil = create_acceuil ();
  color.red = 0xcccc;
  color.green = 0xd645;
  color.blue = 0xd900;
  gtk_widget_modify_bg(acceuil, GTK_STATE_NORMAL, &color);
  gtk_widget_show (acceuil);
  /*menu = create_menu ();
  gtk_widget_show (menu);
  gestionTrp = create_gestionTrp ();
  gtk_widget_show (gestionTrp);
  chercherTrp = create_chercherTrp ();
  gtk_widget_show (chercherTrp);
  calculerTrp = create_calculerTrp ();
  gtk_widget_show (calculerTrp);
  afficherTrp = create_afficherTrp ();
  gtk_widget_show (afficherTrp);
  supprimerTrp = create_supprimerTrp ();
  gtk_widget_show (supprimerTrp);
  gestionFK = create_gestionFK ();
  gtk_widget_show (gestionFK);
  AjouterFK = create_AjouterFK ();
  gtk_widget_show (AjouterFK);
  modifierFK = create_modifierFK ();
  gtk_widget_show (modifierFK);
  supprimerFK = create_supprimerFK ();
  gtk_widget_show (supprimerFK);
  rechercher1FK = create_rechercher1FK ();
  gtk_widget_show (rechercher1FK);
  afficher_rechercherFK = create_afficher_rechercherFK ();
  gtk_widget_show (afficher_rechercherFK);
  consulterFK = create_consulterFK ();
  gtk_widget_show (consulterFK);
  fenetre_acceuil = create_fenetre_acceuil ();
  gtk_widget_show (fenetre_acceuil);
  gestion_capteur = create_gestion_capteur ();
  gtk_widget_show (gestion_capteur);
  fenetre_Ajouter = create_fenetre_Ajouter ();
  gtk_widget_show (fenetre_Ajouter);
  fenetre_Modifier = create_fenetre_Modifier ();
  gtk_widget_show (fenetre_Modifier);
  fenetre_Alarmente = create_fenetre_Alarmente ();
  gtk_widget_show (fenetre_Alarmente);
  deffectueuxFK = create_deffectueuxFK ();
  gtk_widget_show (deffectueuxFK);
  marqueFK = create_marqueFK ();
  gtk_widget_show (marqueFK);
  gestion_ouvrier = create_gestion_ouvrier ();
  gtk_widget_show (gestion_ouvrier);
  Ajouter_ouvrier = create_Ajouter_ouvrier ();
  gtk_widget_show (Ajouter_ouvrier);
  modifier_ouvrier = create_modifier_ouvrier ();
  gtk_widget_show (modifier_ouvrier);
  supprimer_ouvrier = create_supprimer_ouvrier ();
  gtk_widget_show (supprimer_ouvrier);
  consulter_ouvrier = create_consulter_ouvrier ();
  gtk_widget_show (consulter_ouvrier);
  Presence_ouvrier = create_Presence_ouvrier ();
  gtk_widget_show (Presence_ouvrier);
  calcul_taux = create_calcul_taux ();
  gtk_widget_show (calcul_taux);*/

  gtk_main ();
  return 0;
}

