/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_acceuil (void);
GtkWidget* create_menu (void);
GtkWidget* create_gestionTrp (void);
GtkWidget* create_supprimerTrp (void);
GtkWidget* create_chercherTrp (void);
GtkWidget* create_calculerTrp (void);
GtkWidget* create_afficherTrp (void);
GtkWidget* create_gestionFK (void);
GtkWidget* create_ajouterFK (void);
GtkWidget* create_modifierFK (void);
GtkWidget* create_supprimerFK (void);
GtkWidget* create_rechercherFK (void);
GtkWidget* create_afficher_rechFK (void);
GtkWidget* create_consulterFK (void);
GtkWidget* create_fenetre_Accueil (void);
GtkWidget* create_fenetre_Ajouter (void);
GtkWidget* create_fenetre_Modifier (void);
GtkWidget* create_fenetre_Alarmente (void);
GtkWidget* create_gestion_capteur (void);
