/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_acceuil (void);
GtkWidget* create_menu (void);
GtkWidget* create_gestionTrp (void);
GtkWidget* create_supprimerTrp (void);
GtkWidget* create_chercherTrp (void);
GtkWidget* create_calculerTrp (void);
GtkWidget* create_afficherTrp (void);
